# Generated by Django 6.0.4 on 2026-04-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='aliados',
            field=models.TextField(default='Nenhum'),
        ),
    ]
