# Generated by Django 6.0.4 on 2026-04-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_app', '0002_personagem_aliados'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
