# Generated by Django 6.0.4 on 2026-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_app', '0003_personagem_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='afiliacao_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='personagem',
            name='aliados_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personagem',
            name='inimigos_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personagem',
            name='nome_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='afiliacao',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='inimigos',
            field=models.TextField(default='Nenhum'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
