# --- FERRAMENTAS DE TRADUÇÃO ---

# 1. Dicionário Manual para Termos Lore (Geografia, Organizações)
NACOES = {
    "Fire Nation": "Nação do Fogo",
    "Earth Kingdom": "Reino da Terra",
    "Air Nation": "Nação do Ar",
    "Air Nomads": "Nômades do Ar",
    "Water Tribe": "Tribo da Água",
    "United Republic": "República Unida",
    "Metal Clan": "Clã do Metal",
}

CARGOS = {
    "Citizen": "Cidadão",
    "Soldier": "Soldado",
    "Warrior": "Guerreiro",
    "Leader": "Líder",
    "General": "General",
    "Guard": "Guarda",
    "Radio operator": "Operador de Rádio",
    "Earthbender": "Dobrador de Terra",
    "Waterbender": "Dobrador da Água",
    "Airbender": "Dobrador do Ar",
    "Councilwoman": "Conselheira",
    "The Duke": "O Duque",
    "Pet shop owner": "Dono de Pet Shop",
    "Firebender": "Dobrador do Fogo",
    "Freedom Fighters": "Lutadores da Liberdade",
    "Captain": "Capitão",
    "Lieutenant": "Tenente",
    "Commander": "Comandante",
    "Admiral": "Almirante",
    "Sergeant": "Sargento",
    "Officer": "Oficial",
    "Professor": "Professor",
    "Master": "Mestre",
    "Dealer": "Negociante",
    "Doorman": "Porteiro",
    "Wanderer": "Andarilho",
    "Old wanderer": "Velho andarilho",
    "Warehouse worker": "Trabalhador de armazém",
    "Ticket woman": "Vendedora de ingressos",
    "Town authority": "Autoridade local",
    "Royal messenger": "Mensageiro real",
    "Captured agent": "Agente capturado",
    "Calm man": "Homem calmo",
    "Circus master": "Mestre de circo",
    "Circus trainer": "Treinador de circo",
    "Animal control officer": "Agente de controle animal",
    "Flyer distribution man": "Distribuidor de panfletos",
    "Guard post officer": "Oficial de posto de guarda",
    "Outpost soldier": "Soldado de posto avançado",
    "Outpost Soldados": "Soldados de posto avançado",
    "Dai Li sergeant": "Sargento do Dai Li",
    "Air Acolyte woman": "Acólita do Ar",
    "Air Acolyte": "Acólito do Ar",
    "Air Nomad boy": "Garoto Nômade do Ar",
    "Butcher": "Açougueiro",
    "The butcher": "O açougueiro",
    "Nonbender": "Não-dobrador",
    "Metalbender": "Dobrador de Metal",
    "Lavabender": "Dobrador de Lava",
    "Bloodbender": "Dobrador de Sangue",
    "Sandbender": "Dobrador de Areia",
    "Councilman": "Conselheiro",
}

# 2. Lista de Nomes Próprios a NÃO Traduzir (Adicione mais se notar erros)
NOMES_BLOQUEADOS = [
    "Aang", "Katara", "Sokka", "Toph", "Zuko", "Iroh", "Azula", "Appa", "Momo",
    "Korra", "Bolin", "Mako", "Asami", "Tenzin", "Tenzi", "Lin", "Beifong",
    "Su Yin", "Suyin", "Amon", "Zaheer", "Kuvira", "Tarrlok", "Yakone", "Unalaq",
    "Vaatu", "Raava", "Poi", "Ping", "Afiko", "Butakha", "Gun", "Tse", "Sui",
    "Heng", "Chey", "Kyoshi", "Roku", "Kuruk", "Yangchen", "Ummi", "Kya", "Hama",
    "Suki", "Hakoda", "Pakku", "Jinora", "Ikki", "Meelo", "Rohan", "Opal",
    "Desna", "Eska", "Varrick", "Bumi", "How", "Asami Sato", "Toph Beifong",
    "Suyin Beifong", "Zhu Li", "Baatar", "Ghazan", "Ming-Hua", "P'Li",
    "Aiwei", "Tonraq", "Senna", "Wan", "Raiko", "Pema", "Naga", "Pabu",
    "Hiroshi", "Tahno", "Hasook", "Gommu", "Skoochy", "Zolt", "Shady Shin",
    "Two-Toed Ping", "Long Feng", "Jet", "Smellerbee", "Longshot", "Pipsqueak",
    "June", "Pathik", "Bato", "Jee", "Lu Ten", "Mai", "Ty Lee", "Tom-Tom",
    "On Ji", "Hide", "Ruon-Jian", "Shoji", "Yue", "Arnook", "Hahn", "Yugoda",
    "Bosco", "Flopsy", "Miyuki", "Ying", "Ursa", "Ozai", "Sozin", "Azulon",
    "Wan Shi Tong", "Koh", "Hei Bai", "La", "Tui", "Jinzuk", "Rina", "Chan",
    "Ukano", "Xin Fu", "Haru", "Tyro", "Jeong Jeong", "Piandao", "Zhao",
    "Kuei", "Noatak", "Nilak", "Ginger", "Ghazan", "Baatar Jr",
    "Baraz", "Ahnah", "Lian", "Shen", "Macao", "Lily", "Rafa", "Misu",
    "Ran", "Shaw", "Siku", "Sura", "Pik", "Pak", "Ru", "Yaling",
    "Wei", "Wing", "Huan", "Lu", "Gang", "Lo", "Li", "Kaya",
    "Jang Hui", "Filhog", "Ghashiun",
    "Avatar",
]

DICIONARIO_AVATAR = {
    "White Lotus": "Lótus Branca",
    "Fire Ferrets (formerly) Kuvira's army (deserted) Team Avatar Triple Threat Triad (formerly) Republic City Police": "Furões de Fogo (antigo) Exército de Kuvira (desertou) Time Avatar Tríade Tripla (antigo) Polícia de República City",
    "Dai Li Fire Nation (previously Long Feng)": "Dai Li Nação do Fogo (anteriormente Long Feng)",
    "Earth Kingdom Freedom Fighters (separated) Hakoda's forces": "Libertadores do Reino da Terra, Forças de Hakoda",
    "Team Avatar": "Equipe Avatar",
    "Southern Water Tribe": "Tribo da Água do Sul",
    "Northern Water Tribe": "Tribo da Água do Norte",
    "Metal Clan": "Clã do Metal",
    "Agni Kai Triad": "Tríade Agni Kai",
    "Sato family": "Família Sato",

    # Nomes compostos da auditoria
    "Baraz and Ahnah": "Baraz e Ahnah",
    "Broadsword man": "Homem da espada larga",
    "Bumi (Rei of Omashu)": "Bumi (Rei de Omashu)",
    "Combustion Man": "Homem Combustão",
    "Desna and Eska": "Desna e Eska",
    "Dobrador de Metal officer": "Oficial Dobrador de Metal",
    "Fazendeiro e Esposa": "Fazendeiro e Esposa",
    "Fazendeiro and Esposa": "Fazendeiro e Esposa",
    "Filhog (officer)": "Filhog (oficial)",
    "Fire marinha officer": "Oficial da Marinha da Nação do Fogo",
    "Governador of Yi": "Governador de Yi",
    "Head of the Dai Li": "Chefe do Dai Li",
    "Iroh (Forças Unidas General)": "Iroh (General das Forças Unidas)",
    "Jang Hui boy": "Garoto de Jang Hui",
    "Jinzuk and Rina": "Jinzuk e Rina",
    "Kaya (village girl)": "Kaya (garota da vila)",
    "Lian and Shen": "Lian e Shen",
    "Lo and Li": "Lo e Li",
    "Lu and Gang": "Lu e Gang",
    "Macao and Lily": "Macao e Lily",
    "Mãe of Faces": "Mãe dos Rostos",
    "Nação do Fogo Man": "Homem da Nação do Fogo",
    "Nação do Fogo music Professor": "Professor de música da Nação do Fogo",
    "Old Nação do Fogo civilian": "Civil idoso da Nação do Fogo",
    "Old Iron": "Ferro Velho",
    "Old Sweepy": "Velho Vassoura",
    "Pik and Pak": "Pik e Pak",
    "Poi and Ping": "Poi e Ping",
    "Rafa and Misu": "Rafa e Misu",
    "Ran and Shaw": "Ran e Shaw",
    "Roku's waterbending master": "Mestre de dobrar água de Roku",
    "Ru and Yaling": "Ru e Yaling",
    "Senlin Village Lider": "Líder da Vila Senlin",
    "Siku and Sura": "Siku e Sura",
    "Southern Raiders Comandante": "Comandante dos Invasores do Sul",
    "The Big Bad Hippo": "O Grande Hipopótamo Mau",
    "The Boulder": "O Rochedo",
    "The Dark One": "O Sombrio",
    "The Gecko": "O Geco",
    "The Gopher": "O Tatu",
    "Ticket woman": "Vendedora de ingressos",
    "Tribo da Água do Sul boy": "Garoto da Tribo da Água do Sul",
    "Tribo da Água do Sul girl": "Garota da Tribo da Água do Sul",
    "Unnamed Nação do Fogo boy": "Garoto sem nome da Nação do Fogo",
    "Wei and Wing": "Wei e Wing",

    # Afiliações da auditoria
    "Beifong Metalbending Academy Team Beifong Yu Dao": "Academia de Dobrar Metal Beifong, Equipe Beifong, Yu Dao",
    "Bhanti Tribe": "Tribo Bhanti",
    "Cranefish Town Business Council": "Conselho Comercial da Cidade Cranefish",
    "Farming village hospital": "Hospital da vila agrícola",
    "Fire lion turtle city": "Cidade da tartaruga-leão do fogo",
    "Gan Jin tribe": "Tribo Gan Jin",
    "His city": "Sua cidade",
    "Master Yu's Earthbending Academy": "Academia de Dobrar Terra do Mestre Yu",
    "Pirate crew The \"highest bidder\"": "Tripulação pirata — o maior lance",
    "Senlin Village": "Vila Senlin",
    "Southern Raiders": "Invasores do Sul",
    "The White Falls Wolfbats": "Os Morcegos-lobo das Quedas Brancas",
    "Unnamed team": "Equipe sem nome",
    "Zhang tribe": "Tribo Zhang",

    # Aliados da auditoria
    "Chin Village": "Vila Chin",
    "Pântano Nebuloso Tribe": "Tribo do Pântano Nebuloso",
    "Royal Dobrador de Terra Guardas": "Guardas Reais Dobradores de Terra",
    "The Dai Li": "O Dai Li",
    "The Freiras in the": "As Freiras do",
    "Yun and his companions": "Yun e seus companheiros",
    "militares of the Império da Terra": "Militares do Império da Terra",
    "militares of the Império da Terra": "Militares do Império da Terra",

    # Inimigos da auditoria
    "Anyone who threatens the Sun Guerreiro culture or the original source of firebending": "Qualquer um que ameace a cultura dos Guerreiros do Sol ou a fonte original do dobrar fogo",
    "The Diretor": "O Diretor",

    # Nomes da segunda auditoria
    "Ba Sing Se University student": "Estudante da Universidade de Ba Sing Se",
    "Bumi (King of Omashu)": "Bumi (Rei de Omashu)",
    "Cabbage merchant": "Comerciante de repolhos",
    "Farmer and Esposa": "Fazendeiro e Esposa",
    "Fisherman": "Pescador",
    "Fisherman's Esposa": "Esposa do pescador",
    "Governor of Yi": "Governador de Yi",
    "Iroh (United Forces General)": "Iroh (General das Forças Unidas)",
    "Merchant": "Comerciante",
    "Mãe of Faces": "Mãe dos Rostos",
    "Nação do Fogo Man": "Homem da Nação do Fogo",
    "Nação do Fogo music teacher": "Professor de música da Nação do Fogo",
    "Old Nação do Fogo civilian": "Civil idoso da Nação do Fogo",
    "Tribo da Água do Sul boy": "Garoto da Tribo da Água do Sul",
    "Tribo da Água do Sul girl": "Garota da Tribo da Água do Sul",
    "Unnamed Nação do Fogo boy": "Garoto sem nome da Nação do Fogo",

    # Afiliações da segunda auditoria
    "Furões de Fogo (antigo) Exército de Kuvira (desertou) Time Avatar Tríade Tripla (antigo) Polícia de República City": "Furões de Fogo (antigo), Exército de Kuvira (desertou), Equipe Avatar, Tríade Tripla Ameaça (antigo), Polícia de Cidade República",

    # Aliados da segunda auditoria
    "General": "General",
    "Military of the Earth Empire": "Militares do Império da Terra",
    "Mãe of Faces": "Mãe dos Rostos",
    "Pântano Nebuloso Tribe": "Tribo do Pântano Nebuloso",
    "Royal Dobrador de Terra Guardas": "Guardas Reais Dobradores de Terra",
    "The": "O",
    "The nuns in the": "As freiras do",

    # Inimigos da segunda auditoria
    "Anyone who threatens the Sun Guerreiro culture or the original source of firebending": "Qualquer um que ameace a cultura dos Guerreiros do Sol",
    "Military of the Earth Empire": "Militares do Império da Terra",
    "The warden": "O diretor",
}

PARENTESCO_AVATAR = {
    "Aunt": "Tia",
    "Uncle": "Tio",
    "Fire Ferrets": "Furões de Fogo",
    "Husband": "Marido",
    "Wife": "Esposa",
    "Father": "Pai",
    "Mother": "Mãe",
    "Son": "Filho",
    "Daughter": "Filha",
    "Brother": "Irmao",
    "Sister": "Irma",
    "Grandfather": "Avô",
    "Grandmother": "Avó",
}

# Dicionário de alta prioridade — compostos e correções finais
# Verificado PRIMEIRO antes de qualquer outro dicionário
PRIORIDADE_ALTA = {
    # Compostos nação + pessoa
    "Fire Nation man": "Homem da Nação do Fogo",
    "Fire Nation boy": "Garoto da Nação do Fogo",
    "Fire Nation girl": "Garota da Nação do Fogo",
    "Fire Nation civilian": "Civil da Nação do Fogo",
    "Fire Nation soldier": "Soldado da Nação do Fogo",
    "Fire Nation teacher": "Professor da Nação do Fogo",
    "Fire Nation music teacher": "Professor de música da Nação do Fogo",
    "Fire Nation old civilian": "Civil idoso da Nação do Fogo",
    "Water Tribe boy": "Garoto da Tribo da Água",
    "Water Tribe girl": "Garota da Tribo da Água",
    "Water Tribe warrior": "Guerreiro da Tribo da Água",
    "Water Tribe man": "Homem da Tribo da Água",
    "Earth Kingdom boy": "Garoto do Reino da Terra",
    "Earth Kingdom girl": "Garota do Reino da Terra",
    "Earth Kingdom soldier": "Soldado do Reino da Terra",
    "Earth Kingdom man": "Homem do Reino da Terra",
    "Air Nomad boy": "Garoto Nômade do Ar",
    "Air Nomad girl": "Garota Nômade do Ar",
    "Air Nomad man": "Homem Nômade do Ar",
    # Correções finais da 4ª auditoria — versões originais inglês E versões parcialmente traduzidas
    "Farmer and Wife": "Fazendeiro e Esposa",
    "Farmer and Esposa": "Fazendeiro e Esposa",
    "Farmer e Esposa": "Fazendeiro e Esposa",
    "Mother of Faces": "Mãe dos Rostos",
    "Mãe of Faces": "Mãe dos Rostos",
    "Mãe of faces": "Mãe dos Rostos",
    "Water Tribe boy": "Garoto da Tribo da Água do Sul",
    "Water Tribe girl": "Garota da Tribo da Água do Sul",
    "Southern Water Tribe boy": "Garoto da Tribo da Água do Sul",
    "Southern Water Tribe girl": "Garota da Tribo da Água do Sul",
    "Tribo da Água do Sul boy": "Garoto da Tribo da Água do Sul",
    "Tribo da Água do Sul girl": "Garota da Tribo da Água do Sul",
    "Fire Nation civilian": "Civil da Nação do Fogo",
    "Old Fire Nation civilian": "Civil idoso da Nação do Fogo",
    "Old Nação do Fogo civilian": "Civil idoso da Nação do Fogo",
    "Old Civil da Nação do Fogo": "Civil idoso da Nação do Fogo",
    "Unnamed Fire Nation boy": "Garoto sem nome da Nação do Fogo",
    "Unnamed Nação do Fogo boy": "Garoto sem nome da Nação do Fogo",
    "Fire Nation music teacher": "Professor de música da Nação do Fogo",
    "Nação do Fogo music teacher": "Professor de música da Nação do Fogo",
    "Nação do Fogo music Professor": "Professor de música da Nação do Fogo",
    "Fire Nation Man": "Homem da Nação do Fogo",
    "Nação do Fogo Man": "Homem da Nação do Fogo",
    "Air Acolyte Official Avatar Aang Fan Club": "Acólito do Ar — Clube de Fãs Oficial do Avatar Aang",
    "Acólito do Ar Official Avatar Aang Fan Club": "Acólito do Ar — Clube de Fãs Oficial do Avatar Aang",
    "Acólito do Ars Official Avatar Aang Fan Club": "Acólito do Ar — Clube de Fãs Oficial do Avatar Aang",
    "Foggy Swamp Tribe": "Tribo do Pântano Nebuloso",
    "Pântano Nebuloso Tribe": "Tribo do Pântano Nebuloso",
    "Royal Earthbender Guards": "Guardas Reais Dobradores de Terra",
    "Royal Dobrador de Terra Guardas": "Guardas Reais Dobradores de Terra",
    "Anyone who threatens the Sun Warriors culture or the original source of firebending": "Qualquer um que ameace a cultura dos Guerreiros do Sol ou a fonte original do dobrar fogo",
    "Anyone who threatens O Sun Guerreiro culture ou O original source of firebending": "Qualquer um que ameace a cultura dos Guerreiros do Sol ou a fonte original do dobrar fogo",
    "Anyone who threatens the Sun Guerreiro culture or the original source of firebending": "Qualquer um que ameace a cultura dos Guerreiros do Sol ou a fonte original do dobrar fogo",
    "Old Civil da Nação do Fogo": "Civil idoso da Nação do Fogo",
    "Old Nação do Fogo civilian": "Civil idoso da Nação do Fogo",
    "Tribo da Água do Sul boy": "Garoto da Tribo da Água do Sul",
    "Tribo da Água do Sul girl": "Garota da Tribo da Água do Sul",
    "Unnamed Nação do Fogo boy": "Garoto sem nome da Nação do Fogo",
    "Nação do Fogo Man": "Homem da Nação do Fogo",
    "Nação do Fogo music teacher": "Professor de música da Nação do Fogo",
    "Nação do Fogo music Professor": "Professor de música da Nação do Fogo",
    "Mãe of Faces": "Mãe dos Rostos",
    "Mãe of faces": "Mãe dos Rostos",
    "Acólito do Ars Official Avatar Aang Fan Club": "Acólito do Ar — Clube de Fãs Oficial do Avatar Aang",
    "Acólito do Ar Official Avatar Aang Fan Club": "Acólito do Ar — Clube de Fãs Oficial do Avatar Aang",
    "Furões de Fogo (antigo) Exército de Kuvira (desertou) Time Avatar Tríade Tripla (antigo) Polícia de República City": "Furões de Fogo (antigo), Exército de Kuvira (desertou), Equipe Avatar, Tríade Tripla (antigo), Polícia de Cidade República",
    "Pântano Nebuloso Tribe": "Tribo do Pântano Nebuloso",
    "Royal Dobrador de Terra Guardas": "Guardas Reais Dobradores de Terra",
    "Anyone who threatens O Sun Guerreiro culture ou O original source of firebending": "Qualquer um que ameace a cultura dos Guerreiros do Sol ou a fonte original do dobrar fogo",
    "Anyone who threatens the Sun Guerreiro culture or the original source of firebending": "Qualquer um que ameace a cultura dos Guerreiros do Sol ou a fonte original do dobrar fogo",
    "Acólito do Ars Official Avatar Aang Fan Club": "Acólito do Ar — Clube de Fãs Oficial do Avatar Aang",
    "Furões de Fogo (antigo) Exército de Kuvira (desertou) Time Avatar Tríade Tripla (antigo) Polícia de República City": "Furões de Fogo (antigo), Exército de Kuvira (desertou), Equipe Avatar, Tríade Tripla (antigo), Polícia de Cidade República",
    "Anyone who threatens O Sun Guerreiro culture ou O original source of firebending": "Qualquer um que ameace a cultura dos Guerreiros do Sol ou a fonte original do dobrar fogo",
}

LUGARES_AVATAR = {
    "Ba Sing Se": "Ba Sing Se",
    "Omashu": "Omashu",
    "Kyoshi Island": "Ilha Kyoshi",
    "Air Temple Island": "Ilha do Templo do Ar",
    "Northern Air Temple": "Templo do Ar do Norte",
    "Southern Air Temple": "Templo do Ar do Sul",
    "Northern Water Tribe": "Tribo da Água do Norte",
    "Southern Water Tribe": "Tribo da Água do Sul",
    "Republic City": "Cidade República",
    "Spirit World": "Mundo Espiritual",
    "Western Air Temple": "Templo do Ar Ocidental",
    "Eastern Air Temple": "Templo do Ar Oriental",
    "Ember Island": "Ilha Brasa",
    "Kyoshi Island": "Ilha Kyoshi",
    "Crescent Island": "Ilha Crescente",
    "Foggy Swamp": "Pântano Nebuloso",
    "Si Wong Desert": "Deserto Si Wong",
    "Boiling Rock": "Rocha Fervente",
    "Serpent's Pass": "Passagem da Serpente",
    "Zaofu": "Zaofu",
    "Misty Palms Oasis": "Oásis das Palmas Nebulosas",
    "Fire Nation Capital": "Capital da Nação do Fogo",
    "Senlin Village": "Vila Senlin",
    "Chin Village": "Vila Chin",
    "Gan Jin": "Gan Jin",
    "Zhang": "Zhang",
    "Yu Dao": "Yu Dao",
}